# Site settings
# These are used to personalize your new site.
title: Ricardo Harris # your name here
logo: "/images/Self/self.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2040)
  <br />
  <a href="https://example.com/resume">View My Resume</a>
  <br />
  <a href="https://www.linkedin.com/in/Ricardo-Harris/">View My LinkedIn Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  RicoNoSuave # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

