# Site settings
# These are used to personalize your new site.
title: Ricardo Harris # your name here
logo: "/images/Self/self.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  Coder. Cat Dad. Car Nut.<br /><hr />
  <a href="pdf/Resume.pdf">View My Resume</a><br /><br />
  <a href="https://www.linkedin.com/in/Ricardo-Harris/">View My LinkedIn Profile</a>
repository: "csci-csu/csci-portfolio"
github_username:  RicoNoSuave # update with your username
google_analytics: G-4LHEY581DN # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

